### PR TITLE
Dropbox link to VI-Sensor specs

### PR DESCRIPTION
**Pull request by tomlankhorst**
https://www.dropbox.com/s/933c232zjpxzn5h/VISensor_Factsheet_web.pdf?dl=0

### CODE REVIEW

**Comment by schneith** [comment]
Thanks for the upload.

**Comment by JohanEngelen** [comment]
The link is no longer functioning.

**Comment by tomlankhorst** [comment]
https://drive.google.com/file/d/0B6rxbC45JPjAeU91ZVN5UGE4ekU/view?usp=sharing

**Comment by tomlankhorst** [comment]
PR #9

**Pull request merged**
